sweep_config = {
  'method': 'random',  # o 'bayes' o 'grid'
  'metric': {
    'name': 'map_50',  # esta es la métrica que se optimiza
    'goal': 'maximize'
  },
  'parameters': {
    'batch_size': {
      'values': [4, 8, 16]
    },
    'learning_rate': {
      'distribution': 'log_uniform_values',
      'min': 1e-6,
      'max': 1e-2
    },
    'nms_threshold': {  # ❌ Antes tenías 'nms_threshold:' con dos puntos dentro del nombre
      'values': [0.3, 0.5, 0.7]
    },
    'early_stopping_patience': {
      'values': [0, 3, 5]
    }
  }
}